### ISSUE TITLE
Startup Crash

### ISSUE THREAD

**Issue by wizman456** [BrassGoggledCoders/SteamAgeRevolution#11]
hard dependency on JEI

**Comment by wizman456** [comment]
[crash-2018-01-30_16.59.45-client.txt](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a70ed2245534f00138029fa/125516c66e82c728ace21e0d46eb869b308acefbdfb8e70ef40cbdc7797976256751fa6524d0ae2bb34b7e0f1b4d52be011a001ea9aacd39aca43976df5458e8d26d0a73ce3517f9b9811fbf55e972831c83a4a0980e91b6697abad2c51a7c0c0f0a88f85734a5984ccb5df648e14f53ac10242e.txt)

**Comment by FreneticScribbler** [comment]
Hmm
