### ISSUE TITLE
[Suggestion] Steam Spike/Grinder

### ISSUE THREAD

**Issue by KAfable** [BrassGoggledCoders/SteamAgeRevolution#12]
I'm thinking like a rotary drill that turns and grinds up mobs that come into its hitbox. It can be a 1 wide x 2 long x 1 high block (placed in any orientation, and accepts steam from the box half, the other half is the drill). It can be configured to accept steam at different rates, and depending on the rate of steam input, it can spin faster and deal more damage.

**Comment by FreneticScribbler** [comment]
The multiblock API we have isn't really designed for multiblocks in that style, its meant for freeform ones like the boiler. I could hijack it to do something like that, but it wouldn't be ideal.

As for the concept itself, there's the steam vent already implemented which does something similar.
