### ISSUE TITLE
Crash When Right-Clicking Multiblock Blocks

### ISSUE THREAD

**Issue by ChiefLogan3010** [BrassGoggledCoders/SteamAgeRevolution#13]
I'm experiencing a crash when right clicking on a block that is used in a multiblock, I'm unsure if more blocks are affected as my load times are too long to test further, but of the two I have tried each resulted in a crash.

https://gist.github.com/ChiefLogan3010/90650f91776c07d4f4bcb3f47669eed7

**Comment by FreneticScribbler** [comment]
Hmm, I'm not getting anything on my side, even on server. I've tried a couple things - see if the Solid Firebox in particular still crashes you in teh incoming new build.

**Comment by FreneticScribbler** [comment]
Nevermind the above comment, am doof.
