### ISSUE TITLE
Crash when throwing zinc ingot onto steam hammer

### ISSUE THREAD

**Issue by ChiefLogan3010** [BrassGoggledCoders/SteamAgeRevolution#17]
I'm experiencing a crash when throwing a zinc ingot onto the anvil part of the steam powered hammer. Crash Log:
https://gist.github.com/ChiefLogan3010/156d1950461aa15b54a3548c72265ca2

**Comment by ChiefLogan3010** [comment]
Tested with crushing ores and it worked fine, but when I tried it with a brass ingot, the game crashed again, so I'm assuming it's an ingot -> plate problem.

**Comment by FreneticScribbler** [comment]
Weird. Will investigate cheers.
