### ISSUE TITLE
Vat recipes not showing uses of items in JEI

### ISSUE THREAD

**Issue by ChiefLogan3010** [BrassGoggledCoders/SteamAgeRevolution#18]
When clicking 'u' on an item that has a recipe in the vat, such as crushed ore, the vat recipe is not shown, only the smelting one. This works fine for the fluids used in recipes but not the items. As a side note there is also no recipes for the steam furnace in JEI, although I'm not sure if that's just because they're not implemented yet.

**Comment by FreneticScribbler** [comment]
That's intresting. Clearly I still don't quite understand how JEI handles that. Should be easy fix once I figure that out.

As for the steam furnace, there's no JEI because there currently are no unique recipes. Didn't think it would be useful but I see now that it would be.
