### ISSUE TITLE
1.12 Sulphur has no drop

### ISSUE THREAD

**Issue by Zygus42** [BrassGoggledCoders/SteamAgeRevolution#20]
SteamAgeRevolution-1.12.2-0.2.2
base-1.12.2-3.7.1
forge-1.12.2-14.23.3.2673-installer-win

Mining Sulphur ore with a diamond pick creates no drop - not a block or dust or anything.

**Comment by FreneticScribbler** [comment]
Uh hm. Oops.

**Comment by FreneticScribbler** [comment]
...Wrong button.

**Comment by Zygus42** [comment]
You may want to look at this comment:
https://github.com/Brian-Wuest/MC-Prefab/issues/84#issuecomment-386805430
