### ISSUE TITLE
[1.12.2] Empty recipes

### ISSUE THREAD

**Issue by TheSnowyChickens** [BrassGoggledCoders/SteamAgeRevolution#22]
![grafik](https://user-images.githubusercontent.com/29357962/53752430-de84fd80-3eae-11e9-9c8c-b89ea7ebb87f.png)

![grafik](https://user-images.githubusercontent.com/29357962/53752446-e644a200-3eae-11e9-9f59-69aec7a9a4a6.png)

![grafik](https://user-images.githubusercontent.com/29357962/53752520-13915000-3eaf-11e9-9710-92321c72e41a.png)

+ 1 question: why is every furnace recipes, from the same material, (and other recipes) 2 times in the JEI list ?

+ with the Guide - API mod ->
![grafik](https://user-images.githubusercontent.com/29357962/53752963-5a337a00-3eb0-11e9-9749-d55a1c011538.png)

MC: 1.12.2
Forge: 2815
SAR: 0.4.3
Base: 3.12.0
Optifine: No
Other mods: JEI

**Comment by FreneticScribbler** [comment]
Uhhh welp. Could you pastebin your log please?

**Comment by TheSnowyChickens** [comment]
https://pastebin.com/KFuunk4m

I started the game -> joined a world -> opened the inventory -> searched for the mod -> pressed the recipe button on some items from your mod -> leaved the world ->closed the game

**Comment by FreneticScribbler** [comment]
Bad github

**Comment by FreneticScribbler** [comment]
Okay, I have fixed the recipe duplication. As for why GuideAPI support has suddenly stopped working, I'm not sure. I'd advise installing Patchouli!

**Comment by TheSnowyChickens** [comment]
Kk, ty.

**Comment by FreneticScribbler** [comment]
Fixed in 0.4.4
