### ISSUE TITLE
Crash when using fluid IO + Fluid Hopper on a Boiler

### ISSUE THREAD

**Issue by AryaRaiin** [BrassGoggledCoders/SteamAgeRevolution#23]
Steps to replicate:

1.Build successful Steam Boiler.
2.Place fluid hopper going into water input on boiler.
3.Place Fluid IO on top of fluid hopper.
4.Click water bucket on side of Fluid IO.

Crash report: https://pastebin.com/VgE2c53g

SteamAgeRevolution 1.12.2-0.4.3
Currently using in a small modpack and discovered while trying mod progression.

**Comment by FreneticScribbler** [comment]
Well that's thoroughly weird - for one thing, AbstractMethodError should be caught at compile not run time!

**Comment by FreneticScribbler** [comment]
7064674 should fix it, not sure.

**Comment by FreneticScribbler** [comment]
Try 0.4.4 and see if it fixes it please?

**Comment by AryaRaiin** [comment]
Replicated the process in 0.4.4 and it crashed. Here's the crash report. https://pastebin.com/8gruxvYy

Let me know if there's anything else I can do!

**Comment by FreneticScribbler** [comment]
Damn. Er...Working on it

**Comment by FreneticScribbler** [comment]
Could you try this build?
https://ci.blamejared.com/job/SteamAgeRevolution/job/develop/107/
I've tested it myself in and out of dev and no longer get the crash

**Comment by MasterEnderman** [comment]
Doesn't crash for me anymore.

**Comment by FreneticScribbler** [comment]
Ta :+1:
