### ISSUE TITLE
dead inventor causing crash when using rocketfist

### ISSUE THREAD

**Issue by edenhack** [BrassGoggledCoders/SteamAgeRevolution#24]
[crash-2019-04-23_16.29.18-server.txt](https://github.com/BrassGoggledCoders/SteamAgeRevolution/files/3109205/crash-2019-04-23_16.29.18-server.txt)

**Comment by FreneticScribbler** [comment]
Hurm, could have sworn I fixed that. Investigating.

**Comment by edenhack** [comment]
Can confirm after testing it only happens on server. May also be an inconsistently caused by nbt data tacked onto the mob by things such as apotheosis or scaling health? In single player a fresh spawned dead inventory can use the rocket fist no issues.

**Comment by edenhack** [comment]
I can tell you that the dead inventor that caused a crash was invisible from potion effect application by apotheosis or scaling health. Usually the potion effects are 9 minutes long on spawned entities.

**Comment by FreneticScribbler** [comment]
Hmm, weird. Thanks for all the info :)

**Comment by edenhack** [comment]
No problem, thats about all I have for info. I can't really understand much else tacked on in the crash file.

**Comment by FreneticScribbler** [comment]
Somehow the fix I did didn't make it into the version I uploaded to Curse. WTF o.O 

Will reupload shortly.

**Comment by edenhack** [comment]
Sounds good, thanks for the hard work.Sent from my Sprint Samsung Galaxy Note9.
-------- Original message --------From: Arona Jones <notifications@github.com> Date: 4/23/19  2:39 PM  (GMT-06:00) To: BrassGoggledCoders/SteamAgeRevolution <SteamAgeRevolution@noreply.github.com> Cc: Eden Hack <nathancbright@gmail.com>, Author <author@noreply.github.com> Subject: Re: [BrassGoggledCoders/SteamAgeRevolution] dead inventor causing crash when using rocketfist (#24) Somehow the fix I did didn't make it into the version I uploaded to Curse. WTF o.O
Will reupload shortly.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/BrassGoggledCoders/SteamAgeRevolution","title":"BrassGoggledCoders/SteamAgeRevolution","subtitle":"GitHub repository","main_image_url":"https://github.githubassets.com/images/email/message_cards/header.png","avatar_image_url":"https://github.githubassets.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/BrassGoggledCoders/SteamAgeRevolution"}},"updates":{"snippets":[{"icon":"PERSON","message":"@FreneticScribbler in #24: Somehow the fix I did didn't make it into the version I uploaded to Curse. WTF o.O \r\n\r\nWill reupload shortly."}],"action":{"name":"View Issue","url":"https://github.com/BrassGoggledCoders/SteamAgeRevolution/issues/24#issuecomment-485945320"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/BrassGoggledCoders/SteamAgeRevolution/issues/24#issuecomment-485945320",
"url": "https://github.com/BrassGoggledCoders/SteamAgeRevolution/issues/24#issuecomment-485945320",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by FreneticScribbler** [comment]
Try 0.5.0 (also comes with a new tool! :P) whenever Curse approves it.

**Comment by edenhack** [comment]
Will do! Sent from my Sprint Samsung Galaxy Note9.
-------- Original message --------From: Arona Jones <notifications@github.com> Date: 4/23/19  2:51 PM  (GMT-06:00) To: BrassGoggledCoders/SteamAgeRevolution <SteamAgeRevolution@noreply.github.com> Cc: Eden Hack <nathancbright@gmail.com>, Author <author@noreply.github.com> Subject: Re: [BrassGoggledCoders/SteamAgeRevolution] dead inventor causing crash when using rocketfist (#24) Try 0.5.0 (also comes with a new tool! :P) whenever Curse approves it.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/BrassGoggledCoders/SteamAgeRevolution","title":"BrassGoggledCoders/SteamAgeRevolution","subtitle":"GitHub repository","main_image_url":"https://github.githubassets.com/images/email/message_cards/header.png","avatar_image_url":"https://github.githubassets.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/BrassGoggledCoders/SteamAgeRevolution"}},"updates":{"snippets":[{"icon":"PERSON","message":"@FreneticScribbler in #24: Try 0.5.0 (also comes with a new tool! :P) whenever Curse approves it."}],"action":{"name":"View Issue","url":"https://github.com/BrassGoggledCoders/SteamAgeRevolution/issues/24#issuecomment-485949354"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/BrassGoggledCoders/SteamAgeRevolution/issues/24#issuecomment-485949354",
"url": "https://github.com/BrassGoggledCoders/SteamAgeRevolution/issues/24#issuecomment-485949354",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by edenhack** [comment]
so... loaded in, swarm dead inventors slaughtered my ass.... imma say this is fixed. yeah. cool.

**Comment by FreneticScribbler** [comment]
Good good.

Do I need to tune them down a bit? They're meant to be a touch on the brutal side but not overly so

**Comment by edenhack** [comment]
Nah it was a set of 3 of them plus a creeper. Death should have been expected as i was lagging while loading into the server. I think they are fine.
