### ISSUE TITLE
Server Crash on Startup

### ISSUE THREAD

**Issue by edenhack** [BrassGoggledCoders/SteamAgeRevolution#25]
[crash-2019-04-23_21.11.58-server.txt](https://github.com/BrassGoggledCoders/SteamAgeRevolution/files/3109635/crash-2019-04-23_21.11.58-server.txt)

Due to itemdrill now it seems.

**Comment by edenhack** [comment]
Crashes minecraft on startup actually, not just server. Just attempted to load application and failed, same error.

**Comment by FreneticScribbler** [comment]
Whooooooooooops need to do a BASE update too...will release momentarily.

**Comment by edenhack** [comment]
Lol its all good man.

**Comment by FreneticScribbler** [comment]
https://minecraft.curseforge.com/projects/base/files/2702845 should fix it, give it a sec to process

**Comment by edenhack** [comment]
solved after base update.
