### ISSUE TITLE
Fluid Container duplication and Minecraft freezing

### ISSUE THREAD

**Issue by SyntaxError73** [BrassGoggledCoders/SteamAgeRevolution#26]
I just started playing with this mod last night, and I discovered a big bug. If I manually try and insert fluids into any of the containers or multiblock structures provided by this mod using shift right-click, My game will freeze and go unresponsive. There are no crash reports created and no entries in any log files that tell me what went wrong. I have to resort to automatically extracting and sending fluids from the structures and blocks to other containers using fluiducts from Thermal Expansion, because I am very used to shift right-clicking, and often times I forget that if I do this, the game will freeze.

There also seems to be a problem with the fluid IO block. When I transfer fluids into the block from other Fluid IO blocks using a canister, it seems to have a duplication effect of some kind. I end up getting much more of the fluid than I had before. I would have a full tank in one Fluid IO, but using one canister, I could fill up all the Fluid IO blocks. The game freezes when attempting to shift right-click in the GUI of these blocks as well.

I am playing the latest beta 0.5.0 for 1.12.2 and my forge version is 1.12.2-14.23.5.2772

**Comment by FreneticScribbler** [comment]
I've disabled shift click as a work around for the first issue. Actual shift clicking functionality pending...

I can't reproduce the second issue - would you mind opening a second issue with more detail?

**Comment by SyntaxError73** [comment]
It might have been a false observation, since the fluid levels in the containers are normal again. It seemed to have been an error with updating how full the tanks are. Restarting the game reset the amount of fluids to the correct levels.

Also to clarify. I do not crash when shift clicking. The program ceases to respond, and from what I can tell by a logfile, it's an overload of some kind.

> Can't keep up! Did the system time change, or is the server overloaded? Running 11308ms behind, skipping 226 tick(s)

This happened as I froze when shift-clicking items into the multiblock alloy forge.

**Comment by FreneticScribbler** [comment]
Shift click 'fixed' in 0.5.1 - by disabling shift click. Actual shift click functionality coming soon...
