### ISSUE TITLE
[1.12.2] Crash when opening Distiller after inserting steam

### ISSUE THREAD

**Issue by MasterEnderman** [BrassGoggledCoders/SteamAgeRevolution#29]
Forge: 14.23.5.2836
Base: 3.12.1
SteamAgeRevolution: 0.5.1
Crash Report: https://paste.dimdev.org/ituzexorag.mccrash

**Comment by FreneticScribbler** [comment]
Not sure what's going on here

**Comment by MasterEnderman** [comment]
- build distiller
- pump in copper
- pump in steam
- right click the distiller --> Crash Report: https://paste.dimdev.org/iviyiqagix.mccrash

**Comment by FreneticScribbler** [comment]
Yeah, I did the exact same thing and no crash

**Comment by MasterEnderman** [comment]
i think this caused by the Inductive logistic pipes aswell. Just tried some other pipes and i can open the distiller without crashing.

**Comment by FreneticScribbler** [comment]
Weird weird weird. Either I'm doing something strange, or IL is doing something REALLY strange.

**Comment by MasterEnderman** [comment]
wait a moment i think i know what caused this crash, i used a distiller input for the copper slurry and the steam and the distiller only has one fluid input tank but i tried to input to and that caused the index out of bounds error, because i didn't know that you can input steam through the casing (just learned this by building the grinder). So maybe this points in the right direction to fixing this error by disabling insertion of two different fluids if only one is allowed (maybe even allow only these fluids to be inserted, that have a recipe)

**Comment by FreneticScribbler** [comment]
Yeah, that makes a lot more sense. I wasn't limiting fluid insertion like I should have been.
