### ISSUE TITLE
[1.12.2] Steam Hammer Missbehavior

### ISSUE THREAD

**Issue by MasterEnderman** [BrassGoggledCoders/SteamAgeRevolution#30]
Forge: 14.23.5.2836
Base: 3.12.1
SteamAgeRevolution: 0.5.1
![image](https://user-images.githubusercontent.com/24524662/57449530-719a3500-725c-11e9-8480-5185af52b304.png)

The In- and Output slot are both in the top left corner of the gui, so you can't take items out of the hammer. Also the Steam Hammer doesn't need steam to process items and furthermore completes every recipe instantly (0 Seconds Crafting Time)

**Comment by FreneticScribbler** [comment]
Well at least it isn't another crash...
