### ISSUE TITLE
[1.12.2] Steelworks don't produce steel

### ISSUE THREAD

**Issue by MasterEnderman** [BrassGoggledCoders/SteamAgeRevolution#32]
Forge: 14.23.5.2836
Base: 3.12.1
SteamAgeRevolution: 0.5.1
multiblock build correctly, steam / molten iron / coal inserted
![image](https://user-images.githubusercontent.com/24524662/57450219-33057a00-725e-11e9-886e-4f50c9111b35.png)
But it doesn't start producing molten steel.
(furthermore there doesn't seem to be JEI or Crafttweaker integration for the steelworks yet, can those 2 things be added aswell?)

**Comment by FreneticScribbler** [comment]
Welp.

I can add integration too, yep.

**Comment by FreneticScribbler** [comment]
Oh...the main issue is because it requires charcoal to work, not coal. Which JEI support would have told you...working on it.

**Comment by FreneticScribbler** [comment]
I've implemented the requested enhancements and the steel production appears to work correctly when charcoal is used.
