### ISSUE TITLE
[1.12.2] Right clicking fluid io with water bucket places water source

### ISSUE THREAD

**Issue by MasterEnderman** [BrassGoggledCoders/SteamAgeRevolution#37]
Forge: 14.23.5.2836
Base: 3.12.1
SteamAgeRevolution: 0.5.1
Technically the water is duped, because one bucket is tranfered into the fluid io and the other bucket is placed in the world.
![image](https://user-images.githubusercontent.com/24524662/57454037-34d43b00-7268-11e9-8ba3-e2288fe9ae9e.png)

**Comment by FreneticScribbler** [comment]
Huh, I thought that only happened in creative. Oops.

**Comment by MasterEnderman** [comment]
Yeah only happens in creative, but if you do the same thing in survival you'll empty the bucket and instantly open the GUI of the fluid io, which seems unintended aswell.

**Comment by FreneticScribbler** [comment]
It's not ideal, but at least it isn't survival duplication.
