### ISSUE TITLE
[1.12.2] Looking at the Fume Collector spams the console

### ISSUE THREAD

**Issue by MasterEnderman** [BrassGoggledCoders/SteamAgeRevolution#38]
Forge: 14.23.5.2836
Base: 3.12.1
SteamAgeRevolution: 0.5.1
"Spam"*: https://paste.dimdev.org/piqiqehise.mccrash

* I'm using VanillaFix and looking at the fume collector spams my console with the crashreport above

**Comment by FreneticScribbler** [comment]
I suspect this is linked to my packets being buggered and therefore to #33
