### ISSUE TITLE
[1.12.2] Carrier Cart can't be placed

### ISSUE THREAD

**Issue by MasterEnderman** [BrassGoggledCoders/SteamAgeRevolution#46]
Forge: 14.23.5.2836
Base: 3.12.1
SteamAgeRevolution: 0.6.0-SNAPSHOT.118
only a white cube is spawned which falls through the ground into the void. (W.I.P.?)
![image](https://user-images.githubusercontent.com/24524662/57481010-7503df80-72a1-11e9-9640-25c2fd9abd78.png)

**Comment by FreneticScribbler** [comment]
oh lord not this again. I must have broken the entity handling when merging the feature branch into develop.
