### ISSUE TITLE
startup crash

### ISSUE THREAD

**Issue by jonqrandom** [BrassGoggledCoders/SteamAgeRevolution#5]
forge 14.23.0.2501, jre1.8.0_144

https://hastebin.com/uhojukevaj

**Comment by warlordjones** [comment]
**NOOOOOOOoooooooooooo** My worst enemy, scala/actors/threadpool/Arrays!! :P Will upload a fix shortly.

**Comment by warlordjones** [comment]
Fixed in 0.1.1
